/* generated by pull.js */
const manifest = {
  "name": "Block count",
  "description": "Shows the number of blocks a project has.",
  "tags": [],
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber"
    }
  ],
  "userscripts": [
    {
      "url": "blockcount.js"
    }
  ],
  "dynamicEnable": true,
  "dynamicDisable": true
};
export default manifest;
