/* generated by pull.js */
import _import0 from "./userscript.js";
import _import1 from "!css-loader!./userstyle.css";
export const resources = {
  "userscript.js": _import0,
  "userstyle.css": _import1,
};
