/* generated by pull.js */
const resources = {
  "remove-backpack.js": () => require("./remove-backpack.js"),
  "remove-backpack.css": () => require("!css-loader!./remove-backpack.css"),
};
export {resources};
