/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Dangerous customizations",
  "description": "Obscure customization options that few people will want to use. Not recommended.",
  "userscripts": [
    {
      "url": "remove-backpack.js",
      "if": {
        "settings": {
          "removeBackpack": true
        }
      }
    }
  ],
  "userstyles": [
    {
      "url": "remove-backpack.css",
      "if": {
        "settings": {
          "removeBackpack": true
        }
      }
    },
    {
      "url": "remove-feedback.css",
      "if": {
        "settings": {
          "removeFeedback": true
        }
      }
    }
  ],
  "settings": [
    {
      "name": "Remove backpack",
      "id": "removeBackpack",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Remove feedback button",
      "id": "removeFeedback",
      "type": "boolean",
      "default": false
    }
  ],
  "tags": [
    "danger"
  ],
  "enabledByDefault": false
};
export default manifest;
