/* generated by pull.js */
import _import0 from "./remove-backpack.js";
import _import1 from "!css-loader!./remove-backpack.css";
import _import2 from "!css-loader!./remove-feedback.css";
export const resources = {
  "remove-backpack.js": _import0,
  "remove-backpack.css": _import1,
  "remove-feedback.css": _import2,
};
