/* generated by pull.js */
import _resource from "./userscript.js";
import _resource2 from "!css-loader!./search-bar.css";
export const resources = {
  "userscript.js": _resource,
  "search-bar.css": _resource2,
};
