/* generated by pull.js */
import _import0 from "./userscript.js";
import _import1 from "!css-loader!./search-bar.css";
export const resources = {
  "userscript.js": _import0,
  "search-bar.css": _import1,
};
