/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Disable restore points",
  "description": "Disable automatic restore point creation. Does not delete existing restore points.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "danger"
  ],
  "enabledByDefault": false
};
export default manifest;
