/* generated by pull.js */
import _resource from "./remove-backpack.js";
import _resource2 from "!css-loader!./remove-backpack.css";
export const resources = {
  "remove-backpack.js": _resource,
  "remove-backpack.css": _resource2,
};
