/* generated by pull.js */
import _import0 from "!css-loader!./text-bold.css";
import _import1 from "!css-loader!./text-shadow.css";
export const resources = {
  "text-bold.css": _import0,
  "text-shadow.css": _import1,
};
