/* generated by pull.js */
import _resource from "!css-loader!./text-bold.css";
import _resource2 from "!css-loader!./text-shadow.css";
export const resources = {
  "text-bold.css": _resource,
  "text-shadow.css": _resource2,
};
