/* generated by pull.js */
const resources = {
  "userscript.js": () => require("./userscript.js"),
  "style.css": () => require("!css-loader!./style.css"),
  "gamepadlib.css": () => require("!css-loader!./gamepadlib.css"),
};
export {resources};
