/* generated by pull.js */
import _import0 from "./userscript.js";
import _import1 from "!css-loader!./style.css";
import _import2 from "!css-loader!./gamepadlib.css";
export const resources = {
  "userscript.js": _import0,
  "style.css": _import1,
  "gamepadlib.css": _import2,
};
