/* generated by pull.js */
import _resource from "./userscript.js";
import _resource2 from "!css-loader!./style.css";
import _resource3 from "!css-loader!./gamepadlib.css";
export const resources = {
  "userscript.js": _resource,
  "style.css": _resource2,
  "gamepadlib.css": _resource3,
};
