/* generated by pull.js */
import _import0 from "./userscript.js";
import _import1 from "!css-loader!./hideOverflow.css";
import _import2 from "!css-loader!./removeBorder.css";
import _import3 from "!css-loader!./resizeWindow.css";
import _import4 from "!css-loader!./resizeWindow_noToolbar.css";
import _import5 from "!css-loader!./hideToolbar.css";
export const resources = {
  "userscript.js": _import0,
  "hideOverflow.css": _import1,
  "removeBorder.css": _import2,
  "resizeWindow.css": _import3,
  "resizeWindow_noToolbar.css": _import4,
  "hideToolbar.css": _import5,
};
