/* generated by pull.js */
import _resource from "./userscript.js";
import _resource2 from "!css-loader!./hideOverflow.css";
import _resource3 from "!css-loader!./removeBorder.css";
import _resource4 from "!css-loader!./resizeWindow.css";
import _resource5 from "!css-loader!./resizeWindow_noToolbar.css";
import _resource6 from "!css-loader!./hideToolbar.css";
export const resources = {
  "userscript.js": _resource,
  "hideOverflow.css": _resource2,
  "removeBorder.css": _resource3,
  "resizeWindow.css": _resource4,
  "resizeWindow_noToolbar.css": _resource5,
  "hideToolbar.css": _resource6,
};
