/* generated by pull.js */
import _import0 from "./userscript.js";
import _import1 from "!css-loader!./dragged-over.css";
export const resources = {
  "userscript.js": _import0,
  "dragged-over.css": _import1,
};
