/* generated by pull.js */
import _resource from "./userscript.js";
import _resource2 from "!css-loader!./dragged-over.css";
export const resources = {
  "userscript.js": _resource,
  "dragged-over.css": _resource2,
};
