/* generated by pull.js */
const resources = {
  "fix-share-the-love.js": () => require("./fix-share-the-love.js"),
  "stageleft.css": () => require("!css-loader!./stageleft.css"),
};
export {resources};
