/* generated by pull.js */
import _resource from "./fix-share-the-love.js";
import _resource2 from "!css-loader!./stageleft.css";
export const resources = {
  "fix-share-the-love.js": _resource,
  "stageleft.css": _resource2,
};
