/* generated by pull.js */
import _import0 from "./fix-share-the-love.js";
import _import1 from "!css-loader!./stageleft.css";
export const resources = {
  "fix-share-the-love.js": _import0,
  "stageleft.css": _import1,
};
