/* generated by pull.js */
const resources = {
  "sprites.css": () => require("!css-loader!./sprites.css"),
  "costumes.css": () => require("!css-loader!./costumes.css"),
  "sounds.css": () => require("!css-loader!./sounds.css"),
};
export {resources};
