/* generated by pull.js */
import _import0 from "!css-loader!./sprites.css";
import _import1 from "!css-loader!./costumes.css";
import _import2 from "!css-loader!./sounds.css";
export const resources = {
  "sprites.css": _import0,
  "costumes.css": _import1,
  "sounds.css": _import2,
};
