/* generated by pull.js */
import _resource from "!css-loader!./sprites.css";
import _resource2 from "!css-loader!./costumes.css";
import _resource3 from "!css-loader!./sounds.css";
export const resources = {
  "sprites.css": _resource,
  "costumes.css": _resource2,
  "sounds.css": _resource3,
};
